### ISSUE TITLE
Improve Input Focus, Empty Message Handling, and Accessibility in Chat Component in Message.tsx file

### ISSUE THREAD

**Issue by Amansingh0807** [Shobhit2205/RhinoMeet#6]
1. Automatically focus the input field after sending a message for better UX.
2. Trim messages to prevent sending empty spaces.
3. Add aria-label to the input and send button for accessibility improvements.
4. Disable the input field when remoteSocketId is null to avoid confusion.

These changes will enhance usability and ensure a smoother chat experience.

**Comment by Shobhit2205** [comment]
Closed

**Comment by tulovec96** [comment]
Opened
